sudo: required
language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
#  - s3cmd sync --delete-removed -P -M -r public/ s3://continuousfailure.com/
notifications:
    email:
        on_failure: always