author = "jeremy"
baseurl = "https://jeremywho.com/"
canonifyurls = true
languageCode = "en-us"
theme = "hugo-geo"
title = "jeremywho"
paginate = 5

#[Params]
#  AuthorName = "jeremy"
#  cover = "/images/background-cover.png"
#  cv = "/pages/cv"
#  github = "jeremywho"
#  twitter = "jeremywho"



[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
  cover = "/images/background-cover.png"
	showglobe = false
	
	analytics = "code-here"

	github = "https://github.com/jeremywho"
	twitter = "https://twitter.com/jeremywho"
	linkedin = "https://www.linkedin.com/in/jeremydaughhetee"
	email = "jeremy@weebu.com"
	
	#profilepic = "img/profile.png"
	
	title = "jeremywho"
	subtitle = ""
	
	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"